-- Import general settings and such
require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.autocommands")
require("user.wsl")

-- Import plugin configs
require("user.plugins.lsp_config")
require("user.plugins.completions")
-- require "user.plugins.cmp"
require("user.plugins.telescope")
require("user.plugins.nvim-tree")
require("user.plugins.gitsigns")
require("user.plugins.treesitter")
require("user.plugins.autopairs")
require("user.plugins.comment")
require("user.plugins.lualine")
require("user.plugins.toggleterm")
require("user.plugins.project")
require("user.plugins.illuminate")
require("user.plugins.indentline")
require("user.plugins.alpha")
require("user.plugins.dap")
require("user.plugins.trouble")
require("user.plugins.colorizer")
require("user.plugins.typescript")
require("user.plugins.copilot")
require("user.plugins.notify")
require("user.plugins.whichkey")
require("user.plugins.autosave")
require("user.plugins.bufferline")
-- require "user.plugins.wilder"
require("user.plugins.noice")
-- require "user.plugins.lsp_signature"
require("user.plugins.recorder")
require("user.plugins.chatgpt")
